site_name: China Stock Data
site_description: 一个现代化的中国股市数据获取库
site_url: https://sjzsdu.github.io/china_stock_data/
repo_url: https://github.com/sjzsdu/china_stock_data
repo_name: sjzsdu/china_stock_data

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - 首页: index.md
  - 快速开始: getting-started.md
  - API 文档:
      - 概览: api/index.md
      - StockData: api/stock-data.md
      - StockMarket: api/stock-market.md
      - 数据获取器: api/fetchers.md
      - 工具函数: api/utils.md
  - 示例教程:
      - 基础使用: examples/basic.md
  - 开发指南:
      - 贡献指南: contributing.md
      - 变更日志: changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sjzsdu/china_stock_data
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/china_stock_data/

copyright: Copyright &copy; 2024 China Stock Data
